name: Google Cloud Functions Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: file_changes
        name: Check for updated files
        uses: trilom/file-changes-action@v1.2.3
        with:
          prNumber: $
          pushBefore: ''
          pushAfter: ''
      
      - id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_CREDENTIALS }}
          
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1

      - name: Deploy dw-scraper-ups-invoices-scraper-js
        working-directory: ./dw-scraper-ups-invoices-scraper-js
        run: >
          gcloud functions deploy dw-scraper-ups-invoices-scraper-js
          --region=europe-west6
          --entry-point=run
          --timeout=540s
          --runtime=nodejs14
          --trigger-topic=daily-trigger-0700
          --memory=512
        if: contains(steps.file_changes.outputs.files , 'dw-scraper-ups-invoices-scraper-js/')