name: Google Cloud Functions Deploy
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: file_changes
        name: Check for updated files
        uses: trilom/file-changes-action@v1.2.3
        with:
          prNumber: $
          pushBefore: ''
          pushAfter: ''
      
      - id: auth
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ GOOGLE_CLOUD_ENV.GOOGLE_CLOUD_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1

      - name: Deploy yahoo-finance-tickers
        working-directory: ./yahoo-finance-tickers
        run: >
            gcloud functions deploy yahoo-finance-tickers
            --region=europe-west6
            --entry-point=run
            --timeout=540s
            --runtime=python39
            --trigger-topic=yahoo-finance-tickers-trigger
            --memory=4Gi
        if: contains(steps.file_changes.outputs.files , 'yahoo-finance-tickers')
